In [1]:
import tensorflow as tf

In [2]:
x = 3
y = 2
a = tf.add(x, y)
b = tf.multiply(x, y)
with tf.Session() as sess:
    res = sess.run([a, b])
#     print res

In [3]:
# create a graph
a = tf.constant([1.0, 2.0, 3.0], name='a')
b = tf.constant([1.0, 2.0, 3.0], name='b')
c = tf.multiply(a, b)
sess = tf.Session()
print sess.run(c)

[ 1.  4.  9.]


In [4]:
z1 = tf.zeros(shape=[2,3])
print sess.run(z1)
z2 = tf.fill(dims=[2, 3], value=7)
print sess.run(z2)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[7 7 7]
 [7 7 7]]


In [5]:
rn1 = tf.random_normal([2, 3])
print sess.run(rn1)
ru1 = tf.random_uniform([2,3])
print sess.run(ru1)

[[ 0.86694366  0.61069602 -1.19293356]
 [ 1.01292098  2.24589992 -0.99937558]]
[[ 0.30146825  0.22383857  0.72085392]
 [ 0.24562085  0.5488174   0.91992176]]


In [6]:
t_1 = ['apple', 'peach', 'banana']
s = tf.zeros_like(t_1)
print sess.run(s)
t_2 = [[True, False, False],
 [False, False, True],
 [False, True, False]] 
s2 = tf.zeros_like(t_2)
print sess.run(s2)

['' '' '']
[[False False False]
 [False False False]
 [False False False]]


In [7]:
print sess.graph.as_graph_def

<bound method Graph.as_graph_def of <tensorflow.python.framework.ops.Graph object at 0x7fcf89a54d50>>


# constant and variable

In [8]:
v1 = tf.Variable(tf.zeros([2,3]))
init = tf.global_variables_initializer()
sess.run(v1.initializer)
print v1
print v1.eval(session=sess)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32_ref>
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [9]:
v2 = tf.Variable(10, name='v2')
v2.assign(100)
print sess.run(v2.initial_value)
v3 = v2.assign(100)
print sess.run(v3)

10
100


In [10]:
v2 = tf.Variable(10, name='v2')
v3 = v2.assign(v2 * 2)
sess.run(v2.initializer)
print sess.run(v3)
print sess.run(v3)
print sess.run(v3)

20
40
80


# placeholder

In [11]:
a = tf.placeholder(dtype=tf.float32, shape=[3])
b = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)
c = tf.add(a, b)
sess.run(c, {a: [1.0, 2.0, 3.0]})

array([ 2.,  4.,  6.], dtype=float32)

In [16]:
x = tf.random_uniform([])  # Empty array as shape creates a scalar.
y = tf.random_uniform([])
x = tf.constant(2)
y = tf.constant(5)
out = tf.cond(x < y, lambda: tf.add(x, y), lambda: tf.subtract(x, y))
init = tf.global_variables_initializer()
sess2 = tf.Session()
sess2.run(init)
sess2.run(out)

7

In [13]:
x = tf.constant(2)
y = tf.constant(5)
def f1(): return tf.multiply(x, 17)
def f2(): return tf.add(y, 23)
r = tf.cond(tf.less(x, y), f1, f2)
r.eval(session=sess)

34

In [18]:
x = tf.random_uniform([], minval=-1)  # Empty array as shape creates a scalar.
y = tf.random_uniform([], minval=-1)
out = tf.case([(tf.less(x, y), lambda: tf.add(x, y))] , default=lambda: tf.constant(0.0))
# init = tf.variables_initializer([x, y], name='init')
init = tf.global_variables_initializer()
# sess2 = tf.Session()
sess2.run(init)
sess2.run(out)

-0.40258288

In [22]:
x = tf.constant([[0, -2, -1], [0, 1, 2]], shape=[2,3])
y = tf.zeros_like(x)
res = tf.equal(x, y)
print sess2.run(res)

[[ True False False]
 [ True False False]]


In [25]:
a = [29.05088806,  27.61298943,  31.19073486,  29.35532951,
 30.97266006,  26.67541885,  38.08450317,  20.74983215,
 34.94445419,  34.45999146,  29.06485367,  36.01657104,
 27.88236427,  20.56035233,  30.20379066,  29.51215172,
 33.71149445,  28.59134293,  36.05556488,  28.66994858]
x = tf.constant(a)
res = tf.where(x > 30)
print sess2.run(res)
r = tf.gather(x, indices=res)
print sess2.run(r)

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [ 9]
 [11]
 [14]
 [16]
 [18]]
[[ 31.19073486]
 [ 30.97266006]
 [ 38.08450317]
 [ 34.94445419]
 [ 34.45999146]
 [ 36.01657104]
 [ 30.20379066]
 [ 33.71149445]
 [ 36.05556488]]


In [28]:
rg = tf.range(start=1, limit=7)
dm = tf.diag(rg)
print sess2.run(dm)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [31]:
d = tf.random_normal(shape=[10, 10])
md = tf.matrix_determinant(input=d)
print sess2.run(md)

-313.064


In [32]:
ipt = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
ui = tf.unique(x=ipt)
print sess2.run(ui)

Unique(y=array([ 5,  2,  3, 10,  6,  4,  1,  0,  9], dtype=int32), idx=array([0, 1, 2, 0, 3, 4, 1, 2, 5, 1, 6, 6, 7, 8], dtype=int32))


In [38]:
x = tf.random_normal(shape=[100])
y = tf.random_normal(shape=[100])
xsy = tf.subtract(x, y)
sxy = tf.square(xsy)
axy = tf.reduce_mean(xsy)

def mse(): return tf.reduce_mean(sxy)
def abso(): return tf.reduce_sum(tf.abs(xsy))
c = tf.cond(tf.greater(axy, 0), mse, abso)
sess2.run(c)

2.3741705